# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1qmPJWReEROF3yoe3a3e9kGfacyBgO9
"""

import random

file1 = "history is the systematic study of the past"
file2 = "history is the systematic study of the past this is just for practice"




def jaccard_similarity(text1, text2):
    # Split texts into sets of words
    set1 = set(text1.split())
    set2 = set(text2.split())

#The jaccard_simirality function now returns both the simirality score and the set of common words.
#the intersection  variable contains the words that appear in both text1 and text2.
#The common_words set is printed alongside the similarity score.

    # Find the intersection and union
    intersection = set1.intersection(set2)
    union = set1.union(set2)

    # Calculate Jaccard similarity
    similarity = len(intersection) / len(union)

    # Return similarity and intersection words
    return similarity, intersection

# Input texts
text1 = "this is a sample sample text about is this legal sample issues."
text2 = "this text legal discusses legal and ethical this issues in legal computing."

# Calculate similarity and get common words
similarity, common_words = jaccard_similarity(text1, text2)

# Print results
print(f"similarity: {similarity:.2f}")
print(f"common words: {common_words}")